### ISSUE TITLE
建议把tools的文件放到另一个repo

### ISSUE THREAD

**Issue by 0312birdzhang** [AsuraTeam/monitor#1]
clone代码太痛苦了。。。
<code>Receiving objects:  77% (2291/2951), 297.86 MiB | 50 KiB/s</code>

**Comment by lstanyu** [comment]
为国内用户下载方便，同步更新开源中国
请到 https://git.oschina.net/asuramonitor/monitor 下载代码

**Comment by zhaoyun006** [comment]
为国内用户下载方便，同步更新开源中国
请到 https://git.oschina.net/asuramonitor/monitor 下载代码
