### ISSUE TITLE
获取到的脚本信息为[]

### ISSUE THREAD

**Issue by SanderLi** [AsuraTeam/monitor#13]
017-05-19 13:21:31.566  INFO 118040 --- [pool-1-thread-1] c.a.agent.controller.AgentController     : 启动监控上报任务计划
jvm 1    | 2017-05-19 13:21:31.566  INFO 118040 --- [pool-1-thread-1] c.a.agent.controller.AgentController     : 获取脚本文件
jvm 1    | 2017-05-19 13:21:31.566  INFO 118040 --- [pool-1-thread-1] com.asura.agent.util.FileIoUtil          : /home/runtime/monitor/scripts/
jvm 1    | 2017-05-19 13:21:31.566  INFO 118040 --- [pool-1-thread-1] c.a.agent.controller.AgentController     : 获取到脚本文件:[]
jvm 1    | 2017-05-19 13:21:33.066  INFO 118040 --- [pool-1-thread-1] c.a.agent.controller.AgentController     : 完成监控上报任务计划完成
jvm 1    | 2017-05-19 13:21:33.066  INFO 118040 --- [pool-1-thread-1] c.a.agent.controller.AgentController     : 设置脚本信息

1.

**Comment by zhaoyun006** [comment]
这个没问题，这个脚本可以为空
