### ISSUE TITLE
环境都设置好以后，访问出现404

### ISSUE THREAD

**Issue by lstanyu** [AsuraTeam/monitor#2]
访问ip:8081出现404错误，，是哪里的问题？？

**Comment by zhaoyun006** [comment]
1、 /home/runtime/tomcat_8081/webapps/ROOT/ 里面是否有代码
2、一般都是你jdbc没有修改数据库配置，或授权不对
 /home/runtime/tomcat_8081/webapps/ROOT/WEB-INF/classes/jdbc.properties
