### ISSUE TITLE
关于报警的设置问题

### ISSUE THREAD

**Issue by 376631018** [AsuraTeam/monitor#3]
1.报警的具体设置步骤是怎么个流程？
2.关于“报警通道消息配置“页面，配置好后，点上面的“X”按钮关闭不掉，要怎么操作这个关闭？保存页面成功后，再次查看编辑页面的内容，发现“是否开启认证”的勾选项没勾选起来，即这个“是否开启认证”没保存成功，这个是否需要改下？
3.页面中的删除按钮目前都不能操作，这个功能已关闭？

**Comment by zhaoyun006** [comment]
1、报警状态，只有状态为危险时才触发报警，其他状态在监控大盘可以看，但是不会触发报警的。
2、报警通道消息配置页面问题已修复
3、大部分删除功能由于早期权限原因，没有做删除，后期会慢慢都加上的。
