### ISSUE TITLE
部署后不能正常启动tomcat

### ISSUE THREAD

**Issue by agui35303628** [AsuraTeam/monitor#4]
tomcat启动时报以下错误信息：
严重: The web application [] appears to have started a thread named [Thread-229] but has failed to stop it. This is very likely to create a memory leak.

原因是部署后jdbc.properties配置文件的数据库连接被修改为jdbc:mysql://.server:3306/cmdb?useUnicode=true&amp;characterEncoding=UTF-8
导致不能正常连接数据库

**Comment by zhaoyun006** [comment]
这个由于使用deploy.sh造成的，以修复
