### ISSUE TITLE
自己写的脚本的监控项，可以在首页控制台看到报警信息，但是无法实现邮件报警

### ISSUE THREAD

**Issue by zeusYi** [AsuraTeam/monitor#6]
我自己写了一个监控数据库TPS 的Python脚本，脚本如下：
#!/bin/env python
# -*- encoding: utf-8 -*-

import time
import os
import sys
import json
import re
import thread

mysql_stat_list = []

class MySQLMonitorInfo():
    def __init__(self, host, port, user, password):
        self.host = host
        self.port = port
        self.user = user
        self.password = password

    def stat_info(self):
        m = "mysql -umonitor -pmonitor -e 'SHOW GLOBAL STATUS'  "
        data = os.popen(m).readlines()

        Str_string = {}
        for d in data:
            ds = d.replace("  ", "").replace("\t", " ").split(" ")
            Str_string[ds[0]] = ds[1].strip()
        return Str_string

        # 获取差值

# 5 秒
def get_d_value(key, data1, data2):
    try:
        data = (int(data2.get(key, 0)) - int(data1.get(key, 0))) / 5
    except Exception:
        data = 0
    return data

def get_data(host, tid):
    try:
        # 如果加密码的话就调用远程机器
        conn = MySQLMonitorInfo(host, int(sys.argv[2]), sys.argv[3], sys.argv[4])
    except Exception:
        #  本地无密码操作
        conn = MySQLMonitorInfo("", "", "", "")
    stat_info = conn.stat_info()
    time.sleep(5)
    stat_info_2 = conn.stat_info()

    monitor_keys = [
        ('Com_select', 'COUNTER'),
        ('Qcache_hits', 'COUNTER'),
        ('Com_insert', 'COUNTER'),
        ('Com_update', 'COUNTER'),
        ('Com_delete', 'COUNTER'),
        ('Com_replace', 'COUNTER'),
        ('MySQL_QPS', 'COUNTER'),
        ('MySQL_TPS', 'COUNTER'),
        ('Innodb_buffer_pool_read_requests', 'COUNTER'),
        ('Innodb_buffer_pool_reads', 'COUNTER'),
        ('Innodb_buffer_pool_pages_flushed', 'COUNTER'),

        ('ReadWrite_ratio', 'GAUGE'),
        ('Innodb_buffer_read_hit_ratio', 'GAUGE'),
        ('Innodb_buffer_pool_pages_free', 'GAUGE'),
        ('Innodb_buffer_pool_pages_dirty', 'GAUGE'),
        ('Innodb_buffer_pool_pages_data', 'GAUGE'),

        ('Bytes_received', 'COUNTER'),
        ('Bytes_sent', 'COUNTER'),
        ('Innodb_rows_deleted', 'COUNTER'),
        ('Innodb_rows_inserted', 'COUNTER'),
        ('Innodb_rows_read', 'COUNTER'),
        ('Innodb_rows_updated', 'COUNTER'),
        ('Innodb_os_log_fsyncs', 'COUNTER'),
        ('Innodb_os_log_written', 'COUNTER'),
        ('Created_tmp_disk_tables', 'COUNTER'),
        ('Created_tmp_tables', 'COUNTER'),
        ('Connections', 'COUNTER'),
        ('Innodb_log_waits', 'COUNTER'),
        ('Slow_queries', 'COUNTER'),
        ('Binlog_cache_disk_use', 'COUNTER')
    ]
    select = get_d_value("Com_select", stat_info, stat_info_2)
    update = get_d_value("Com_update", stat_info, stat_info_2)
    delete = get_d_value("Com_delete", stat_info, stat_info_2)
    insert = get_d_value("Com_insert", stat_info, stat_info_2)
    replace = get_d_value("replace", stat_info, stat_info_2)
    Innodb_buffer_pool_read_requests = get_d_value("Innodb_buffer_pool_read_requests", stat_info, stat_info_2)

    for _key, falcon_type in monitor_keys:
        if _key == 'MySQL_QPS':
            _value = select + get_d_value("Qcache_hits", stat_info, stat_info_2)
        elif _key == 'MySQL_TPS':
            _value = insert + update + delete + replace
        elif _key == 'Innodb_buffer_read_hit_ratio':
            try:
                _value = round((Innodb_buffer_pool_read_requests - get_d_value("Innodb_buffer_pool_reads", stat_info,
                                                                               stat_info_2)) / Innodb_buffer_pool_read_requests * 100,
                               3)
            except ZeroDivisionError:
                _value = 0
        elif _key == 'ReadWrite_ratio':
            try:
                _value = round((select + get_d_value("Qcache_hits", stat_info, stat_info_2)) / (
                    insert + update + delete + replace), 2)
            except ZeroDivisionError:
                _value = 0
        else:
            if falcon_type == "COUNTER":
                _value = get_d_value(_key, stat_info, stat_info_2)
            else:
                _value = int(stat_info.get(_key, 0))

        result = {
            'name': '%s' % (_key.replace("_", ".")),
            'groups': "MysqlNew",
            'value': _value,
            'status': 1,
            'command': sys.argv[0],
            'messages': "%s %s" % (_key, _value),
        }
        if host and "local" not in host:
            result["ip"] = host
        # print("111")
        # print(result)
        # print("2222")
        if result['name'] == 'MySQL.TPS' and result['value'] >= 10:
            # print(result)
            result['status'] = 2
            print(
            json.dumps([result]))
        # mysql_stat_list.append(result)
        elif result['name'] == 'MySQL.TPS' and result['value'] < 10:
            result['status'] = 1
            print(
            json.dumps([result]))

if len(sys.argv) > 4:
    for host in sys.argv[1].split(","):
        thread.start_new_thread(get_data, (host, 1))
    time.sleep(5.1)
else:
    get_data("", "")
print
json.dumps(mysql_stat_list)                                                                                                                                 

逻辑是当TPS >=10 的时候就触发报警--- 返回的json 中status=2，如果TPS <10 status=1。

现在已经实现了数据上报，并且可以在server端看到报警信息，但是不能触发邮件的报警，

我已经配置了监控项，和单机监控，并且配置了报警组，邮件smtp也正常，赵云大神帮我测试了redis读写是可以发出邮件的，但是为什么我自己的脚本，可以在web上反馈到报警信息，但是就是无法触发邮件报警。！！！    @zhaoyun006  帮我解决下！ QQ: 天堂向左，北京向右

**Comment by zhaoyun006** [comment]
如果返回为2的话，就需要去监控配置里将报警接收人加上就OK了，其他的没有什么
