### ISSUE TITLE
mvn报错

### ISSUE THREAD

**Issue by xiaosadexiaohai** [AsuraTeam/monitor#8]
跑脚本mvn报错
[INFO] ------------------------------------------------------------------------
[INFO] Building Monitor 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ Monitor ---
[INFO] Deleting /opt/monitor-bak/server/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Monitor ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 46 resources
[INFO] Copying 12 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ Monitor ---
[INFO] Compiling 321 source files to /opt/monitor-bak/server/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /opt/monitor-bak/server/src/main/java/com/asura/util/HttpUtil.java:[5,33] Handler is internal proprietary API and may be removed in a future release
[ERROR] /opt/monitor-bak/server/src/main/java/com/asura/util/Base64Util.java:[3,15] BASE64Decoder is internal proprietary API and may be removed in a future release
[ERROR] /opt/monitor-bak/server/src/main/java/com/asura/util/Base64Util.java:[4,15] BASE64Encoder is internal proprietary API and may be removed in a future release
[ERROR] /opt/monitor-bak/server/src/main/java/com/asura/resource/controller/ResourceReportController.java:[6,31] error: package com.sun.tools.javac.comp does not exist
[ERROR] /opt/monitor-bak/server/src/main/java/com/asura/util/HttpUtil.java:[298,58] Handler is internal proprietary API and may be removed in a future release
[ERROR] /opt/monitor-bak/server/src/main/java/com/asura/util/Base64Util.java:[33,24] BASE64Encoder is internal proprietary API and may be removed in a future release
[ERROR] /opt/monitor-bak/server/src/main/java/com/asura/util/Base64Util.java:[43,16] BASE64Decoder is internal proprietary API and may be removed in a future release
[ERROR] /opt/monitor-bak/server/src/main/java/com/asura/util/Base64Util.java:[43,44] BASE64Decoder is internal proprietary API and may be removed in a future release
[INFO] 8 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.258s
[INFO] Finished at: Sun May 14 20:33:57 CST 2017
[INFO] Final Memory: 16M/219M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project Monitor: Compilation failure: Compilation failure:
[ERROR] /opt/monitor-bak/server/src/main/java/com/asura/util/HttpUtil.java:[5,33] Handler is internal proprietary API and may be removed in a future release
[ERROR] /opt/monitor-bak/server/src/main/java/com/asura/util/Base64Util.java:[3,15] BASE64Decoder is internal proprietary API and may be removed in a future release
[ERROR] /opt/monitor-bak/server/src/main/java/com/asura/util/Base64Util.java:[4,15] BASE64Encoder is internal proprietary API and may be removed in a future release
[ERROR] /opt/monitor-bak/server/src/main/java/com/asura/resource/controller/ResourceReportController.java:[6,31] error: package com.sun.tools.javac.comp does not exist
[ERROR] /opt/monitor-bak/server/src/main/java/com/asura/util/HttpUtil.java:[298,58] Handler is internal proprietary API and may be removed in a future release
[ERROR] /opt/monitor-bak/server/src/main/java/com/asura/util/Base64Util.java:[33,24] BASE64Encoder is internal proprietary API and may be removed in a future release
[ERROR] /opt/monitor-bak/server/src/main/java/com/asura/util/Base64Util.java:[43,16] BASE64Decoder is internal proprietary API and may be removed in a future release
[ERROR] /opt/monitor-bak/server/src/main/java/com/asura/util/Base64Util.java:[43,44] BASE64Decoder is internal proprietary API and may be removed in a future release
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by zhaoyun006** [comment]
package com.sun.tools.javac.comp does not exist 这个已删除，再试下

**Comment by xiaosadexiaohai** [comment]
ok 已解决 编译成功
