### ISSUE TITLE
登录权限问题

### ISSUE THREAD

**Issue by xiaosadexiaohai** [AsuraTeam/monitor#9]
现在这套监控想要查看机器性能监控 不需要帐号密码的,虽然放在内网,但是一般监控给予主管级别看的,如果没设置查看监控需要帐号密码这样只要知道地址就可以随意看机器状况

**Comment by xiaosadexiaohai** [comment]
一旦没帐号密码 是不允许查看的

**Comment by zhaoyun006** [comment]
这个可以设置权限的，监控目前需求是所有人都可以看，你自己可以去配置监控权限，所有的访问都可以拦截，为了方便给大家看，不是光运维或某个领导看，是所有技术人员参与的，包括监控配置，都是各方业务自己去添加的。
